# Catppuccin Macchiato Starship Prompt
format = """
[](#CAD3F5)\
$os\
$username\
[](bg:#A5ADCB fg:#24273A)\
$directory\
[](fg:#A5ADCB bg:#8AADF4)\
$git_branch\
$git_status\
[](fg:#8AADF4 bg:#F5A97F)\
$c\
$rust\
$golang\
$python\
$java\
$nodejs\
$scala\
[](fg:#F5A97F bg:#A6DA95)\
$docker_context\
[](fg:#A6DA95 bg:#0000)\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:#24273A fg:#CAD3F5"
format = "[ $symbol]($style)"

[os.symbols]
nixos = "❄"
macos = "🍎"
linux = "🐧"

[username]
show_always = true
style_user = "bg:#CAD3F5 fg:#24273A"
style_root = "bg:#CAD3F5 fg:#ED8796"
format = "[ $user ]($style)"

[directory]
style = "fg:#24273A bg:#A5ADCB"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bg:#8AADF4"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#8AADF4"
format = '[$all_status$ahead_behind]($style)'

[c]
style = "bg:#F5A97F"
format = "[ $symbol$version ]($style)"
disabled = false

[rust]
style = "bg:#F5A97F"
format = "[ $symbol$version ]($style)"

[golang]
style = "bg:#F5A97F"
format = "[ $symbol$version ]($style)"

[python]
style = "bg:#F5A97F"
format = "[ $symbol$version ]($style)"

[java]
style = "bg:#F5A97F"
format = "[ $symbol$version ]($style)"

[nodejs]
style = "bg:#F5A97F"
format = "[ $symbol$version ]($style)"

[scala]
style = "bg:#F5A97F"
format = "[ $symbol$version ]($style)"

[docker_context]
style = "bg:#A6DA95"
format = "[ $symbol$context ]($style)"
only_with_files = true

[cmd_duration]
style = "bg:#1E2030 fg:#A5ADCB"
format = "[ ⏱ $duration ]($style)"
min_time = 2000

[character]
success_symbol = "[❯](bold #A6DA95)"
error_symbol = "[❯](bold #ED8796)"
vimcmd_symbol = "[❮](bold #8AADF4)"
format = "$symbol"